#!/usr/bin/env bash

echo "Loading alias..."

alscreate () {
  if [ "$1" == "-h" -o "$#" -lt 2 ]; then
	echo "Usage: alscreate alsname \"cmd -p arg1 arg2\""
  else
	echo "alias" $1'="'$2'"' >> ~/.sections/alias
	source ~/.sections/alias
  fi
}


# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias s='ls -CF'

alias cd..="cd .."
alias ..="cd .."
alias ..2="cd ../.."
alias ..3="cd ../../.."
alias ..4="cd ../../../.."
alias ..5="cd ../../../../.."
alias ..6="cd ../../../../../.."
alias ..7="cd ../../../../../../.."

alias reboot="sudo shutdown -r now"
alias fn="find . -name"
alias gogo="source ~/.bashrc"
alias install="sudo apt install"
alias update="sudo apt-get update"
alias upgrade="sudo apt-get upgrade"
alias remove="sudo apt-get autoremove"
alias searchlocal="sudo apt-cache search"
alias searchuniverse="sudo apt search"
alias home="cd ~"
alias ..ls="cd .. && ls"
