#!/usr/bin/env bash

echo "Loading android..."

# Android builds should be using SD card, not eMMC for boot storage
export BUILD_TARGET_DEVICE=sd
export ARCH=arm
export CROSS_COMPILE=~/Android/Source/newdroid/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/bin/arm-linux-androideabi-

alias git-android-status='git status | egrep -v "kernel_imx|bootable|out"'

fslsdpart() {
         if [ "$1" == "-h" ]; then
                 echo "Usage: 'fsl-sd-part /dev/sdx' "
         elif [ "${1%/*}" == "/dev" ]; then
		 mypath=`pwd`
		 echo "Preparing disk..."
		 sudo umount `echo "$1?*"` 2> /dev/null  
		 sudo partprobe $1
                 croot
                 cd out/target/product/sabresd_6dq
                 echo "Partitioning disk..."
                 yes | sudo ../../../../device/fsl/common/tools/fsl-sdcard-partition.sh -f imx6q $1
         	 cd $mypath
         else
                echo "Bad argument."
         fi
}

#promptFunction() {

#   if [ "$PWD" != "$OLDPWD" ] && [ -e ./build/envsetup.sh ]; then
#	OLDPWD="$PWD";
#	source ./build/envsetup.sh > /dev/null
#	chooseproduct sabresd_6dq > /dev/null
#	choosevariant eng > /dev/null
#	echo "Setup Complete."
#   fi
#   export PROMPT_COMMAND=promptFunction
#}

# function cd () { builtin cd "$@" && promptFunction; } # recursive issue
#export PROMPT_COMMAND=promptFunction
