#!/usr/bin/env bash

# Android builds should be using SD card, not eMMC for boot storage
export BUILD_TARGET_DEVICE=sd
export ARCH=arm

alias git-android-status='git status -uno | egrep -v "out|*generated*"'

android-setup() {
	if [ -d build/ ]; then
		export CURRENT_DROID=`pwd`
		export CROSS_COMPILE=$CURRENT_DROID/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/bin/arm-linux-androideabi-
		. build/envsetup.sh
		lunch
	else
		echo "Not an Android directory"
	fi
}

fslsdpart() {
         if [ "$1" == "-h" ]; then
                 echo "Usage: 'fsl-sd-part /dev/sdx' "
         elif [ "${1%/*}" == "/dev" ]; then
		 mypath=`pwd`
		 echo "Preparing disk..."
		 sudo umount `echo "$1?*"` 2> /dev/null  
		 sudo partprobe $1
                 croot
                 cd out/target/product/sabresd_6dq
                 echo "Partitioning disk..."
                 yes | sudo ../../../../device/fsl/common/tools/fsl-sdcard-partition.sh -f imx6q $1
         	 cd $mypath
         else
                echo "Bad argument."
         fi
}

lookup-error() {
         if [ "$1" == "-h" ]; then
                 echo "Usage: 'lookup-error [#]' "
         else
		 grep -irs --no-filename "\s$1\s" kernel_imx/include/uapi/asm-generic/errno*
         fi
}

